name: Special Cases CI

on: [pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      GTSAM_BUILD_UNSTABLE: ON

    strategy:
      fail-fast: false

      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name:
          [
            ubuntu-gcc-deprecated,
            ubuntu-gcc-quaternions,
            ubuntu-gcc-tbb,
          ]

        build_type: [Debug, Release]

        include:
          - name: ubuntu-gcc-deprecated
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
            flag: deprecated

          - name: ubuntu-gcc-quaternions
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
            flag: quaternions

          - name: ubuntu-gcc-tbb
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
            flag: tbb

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          # LLVM 9 is not in Bionic's repositories so we add the official LLVM repository.
          if [ "${{ matrix.compiler }}" = "clang" ] && [ "${{ matrix.version }}" = "9" ]; then
            sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
          fi
          sudo apt-get -y update

          sudo apt install cmake build-essential pkg-config libpython-dev python-numpy

          echo "::set-env name=BOOST_ROOT::$(echo $BOOST_ROOT_1_69_0)"
          echo "::set-env name=LD_LIBRARY_PATH::$(echo $BOOST_ROOT_1_69_0/lib)"

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
            echo "::set-env name=CC::gcc-${{ matrix.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.version }}"
          else
            sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
            echo "::set-env name=CC::clang-${{ matrix.version }}"
            echo "::set-env name=CXX::clang++-${{ matrix.version }}"
          fi

      - name: Install (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja boost
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            brew install gcc@${{ matrix.version }}
            echo "::set-env name=CC::gcc-${{ matrix.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.version }}"
          else
            sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
            fi

      - name: Set Allow Deprecated Flag
        if: matrix.flag == 'deprecated'
        run: |
          echo "::set-env name=GTSAM_ALLOW_DEPRECATED_SINCE_V41::ON"
          echo "Allow deprecated since version 4.1"

      - name: Set Use Quaternions Flag
        if: matrix.flag == 'quaternions'
        run: |
          echo "::set-env name=GTSAM_USE_QUATERNIONS::ON"
          echo "Use Quaternions for rotations"

      - name: Set GTSAM_WITH_TBB Flag
        if: matrix.flag == 'tbb'
        run: |
          echo "::set-env name=GTSAM_WITH_TBB::ON"
          echo "GTSAM Uses TBB"

      - name: Build & Test
        run: |
          bash .github/scripts/unix.sh -t
